name: multi
on:
  push:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action