name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "job1 done"

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: echo
      run: echo "job2 done"
    
jobs:
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - name: echo
      run: echo "job3 done"

jobs:
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
    - name: echo
      run: echo "job4 done"