name: path-filter
on:
  push:
    paths:
    - '.github/workflows/part1/*'
    - '!.github/workflows/part1/push.yaml'
jobs:
 no-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello